/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APCredentials } from '../models';
// @ts-ignore
import type { Device } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * ApApi - axios parameter creator
 * @export
 */
export const ApApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Bring the AP connection down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apDownWifiApDownPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/ap/down`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify AP settings: SSID, optional WPA2 PSK, and autoconnect flag.
         * @summary Ap Modify
         * @param {APCredentials} aPCredentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apModifyWifiApModifyPost: async (aPCredentials: APCredentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'aPCredentials' is not null or undefined
            assertParamExists('apModifyWifiApModifyPost', 'aPCredentials', aPCredentials)
            const localVarPath = `/wifi/ap/modify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(aPCredentials, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get just the SSID, PSK (if any), and autoconnect flag from the AP profile.
         * @summary Ap Show Credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apShowCredentialsWifiApShowGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/ap/show`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bring the AP connection up; optionally modify parameters first.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apUpWifiApUpPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/ap/up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Count Stations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countStationsWifiApCountPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/ap/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiStatusWifiApDeviceStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/ap/device/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApApi - functional programming interface
 * @export
 */
export const ApApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApApiAxiosParamCreator(configuration)
    return {
        /**
         * Bring the AP connection down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apDownWifiApDownPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apDownWifiApDownPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.apDownWifiApDownPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify AP settings: SSID, optional WPA2 PSK, and autoconnect flag.
         * @summary Ap Modify
         * @param {APCredentials} aPCredentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apModifyWifiApModifyPost(aPCredentials: APCredentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apModifyWifiApModifyPost(aPCredentials, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.apModifyWifiApModifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get just the SSID, PSK (if any), and autoconnect flag from the AP profile.
         * @summary Ap Show Credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apShowCredentialsWifiApShowGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APCredentials>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apShowCredentialsWifiApShowGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.apShowCredentialsWifiApShowGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bring the AP connection up; optionally modify parameters first.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apUpWifiApUpPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apUpWifiApUpPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.apUpWifiApUpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Count Stations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async countStationsWifiApCountPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.countStationsWifiApCountPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.countStationsWifiApCountPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiStatusWifiApDeviceStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiStatusWifiApDeviceStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApApi.wifiStatusWifiApDeviceStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApApi - factory interface
 * @export
 */
export const ApApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApApiFp(configuration)
    return {
        /**
         * Bring the AP connection down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apDownWifiApDownPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apDownWifiApDownPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Modify AP settings: SSID, optional WPA2 PSK, and autoconnect flag.
         * @summary Ap Modify
         * @param {APCredentials} aPCredentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apModifyWifiApModifyPost(aPCredentials: APCredentials, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apModifyWifiApModifyPost(aPCredentials, options).then((request) => request(axios, basePath));
        },
        /**
         * Get just the SSID, PSK (if any), and autoconnect flag from the AP profile.
         * @summary Ap Show Credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apShowCredentialsWifiApShowGet(options?: RawAxiosRequestConfig): AxiosPromise<APCredentials> {
            return localVarFp.apShowCredentialsWifiApShowGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Bring the AP connection up; optionally modify parameters first.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apUpWifiApUpPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apUpWifiApUpPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Count Stations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        countStationsWifiApCountPost(options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.countStationsWifiApCountPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiStatusWifiApDeviceStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<Device> {
            return localVarFp.wifiStatusWifiApDeviceStatusGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApApi - object-oriented interface
 * @export
 * @class ApApi
 * @extends {BaseAPI}
 */
export class ApApi extends BaseAPI {
    /**
     * Bring the AP connection down.
     * @summary Ap Down
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public apDownWifiApDownPost(options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).apDownWifiApDownPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify AP settings: SSID, optional WPA2 PSK, and autoconnect flag.
     * @summary Ap Modify
     * @param {APCredentials} aPCredentials 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public apModifyWifiApModifyPost(aPCredentials: APCredentials, options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).apModifyWifiApModifyPost(aPCredentials, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get just the SSID, PSK (if any), and autoconnect flag from the AP profile.
     * @summary Ap Show Credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public apShowCredentialsWifiApShowGet(options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).apShowCredentialsWifiApShowGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Bring the AP connection up; optionally modify parameters first.
     * @summary Ap Up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public apUpWifiApUpPost(options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).apUpWifiApUpPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Count Stations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public countStationsWifiApCountPost(options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).countStationsWifiApCountPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Wifi Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApApi
     */
    public wifiStatusWifiApDeviceStatusGet(options?: RawAxiosRequestConfig) {
        return ApApiFp(this.configuration).wifiStatusWifiApDeviceStatusGet(options).then((request) => request(this.axios, this.basePath));
    }
}

