/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DevModeStatus } from '../models';
// @ts-ignore
import type { DevModeToggle } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * DevModeApi - axios parameter creator
 * @export
 */
export const DevModeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Dev mode is TRUE if CORE_CFG == DEV_MODE_CORE_CFG, FALSE if CORE_CFG == OEM_CORE_CFG, ERROR otherwise.
         * @summary Get Dev Mode Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevModeStatusDevModeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dev_mode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a timestamped backup of the current dev-mode working directory. Only valid while dev mode is enabled.
         * @summary Manual Backup
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        manualBackupDevModeBackupPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dev_mode/backup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Refresh the developer-mode working copy from OEM core. Only valid while dev mode is enabled.  Steps:   * backup DEV_MODE_DIR to backups/<timestamp> (excluding backups)   * clear DEV_MODE_DIR except \'backups\'   * copy OEM_CORE_DIR into DEV_MODE_DIR
         * @summary Refresh Dev Mode Config
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshDevModeConfigDevModeRefreshPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dev_mode/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable/disable Developer Mode.  - true from false:     * backup existing DEV_MODE_DIR if it exists     * refresh DEV_MODE_DIR from OEM_CORE_DIR     * set cm4 flag     * set CORE_CFG to DEV_MODE_CORE_CFG     * restart klipper - false from true:     * set CORE_CFG to OEM_CORE_CFG     * restart klipper - no state change: no-op
         * @summary Set Dev Mode
         * @param {DevModeToggle} devModeToggle 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setDevModeDevModePost: async (devModeToggle: DevModeToggle, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'devModeToggle' is not null or undefined
            assertParamExists('setDevModeDevModePost', 'devModeToggle', devModeToggle)
            const localVarPath = `/dev_mode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(devModeToggle, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DevModeApi - functional programming interface
 * @export
 */
export const DevModeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DevModeApiAxiosParamCreator(configuration)
    return {
        /**
         * Dev mode is TRUE if CORE_CFG == DEV_MODE_CORE_CFG, FALSE if CORE_CFG == OEM_CORE_CFG, ERROR otherwise.
         * @summary Get Dev Mode Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevModeStatusDevModeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevModeStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevModeStatusDevModeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevModeApi.getDevModeStatusDevModeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a timestamped backup of the current dev-mode working directory. Only valid while dev mode is enabled.
         * @summary Manual Backup
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async manualBackupDevModeBackupPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.manualBackupDevModeBackupPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevModeApi.manualBackupDevModeBackupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Refresh the developer-mode working copy from OEM core. Only valid while dev mode is enabled.  Steps:   * backup DEV_MODE_DIR to backups/<timestamp> (excluding backups)   * clear DEV_MODE_DIR except \'backups\'   * copy OEM_CORE_DIR into DEV_MODE_DIR
         * @summary Refresh Dev Mode Config
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshDevModeConfigDevModeRefreshPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshDevModeConfigDevModeRefreshPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevModeApi.refreshDevModeConfigDevModeRefreshPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable/disable Developer Mode.  - true from false:     * backup existing DEV_MODE_DIR if it exists     * refresh DEV_MODE_DIR from OEM_CORE_DIR     * set cm4 flag     * set CORE_CFG to DEV_MODE_CORE_CFG     * restart klipper - false from true:     * set CORE_CFG to OEM_CORE_CFG     * restart klipper - no state change: no-op
         * @summary Set Dev Mode
         * @param {DevModeToggle} devModeToggle 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setDevModeDevModePost(devModeToggle: DevModeToggle, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevModeStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setDevModeDevModePost(devModeToggle, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevModeApi.setDevModeDevModePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DevModeApi - factory interface
 * @export
 */
export const DevModeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DevModeApiFp(configuration)
    return {
        /**
         * Dev mode is TRUE if CORE_CFG == DEV_MODE_CORE_CFG, FALSE if CORE_CFG == OEM_CORE_CFG, ERROR otherwise.
         * @summary Get Dev Mode Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevModeStatusDevModeGet(options?: RawAxiosRequestConfig): AxiosPromise<DevModeStatus> {
            return localVarFp.getDevModeStatusDevModeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Create a timestamped backup of the current dev-mode working directory. Only valid while dev mode is enabled.
         * @summary Manual Backup
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        manualBackupDevModeBackupPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.manualBackupDevModeBackupPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Refresh the developer-mode working copy from OEM core. Only valid while dev mode is enabled.  Steps:   * backup DEV_MODE_DIR to backups/<timestamp> (excluding backups)   * clear DEV_MODE_DIR except \'backups\'   * copy OEM_CORE_DIR into DEV_MODE_DIR
         * @summary Refresh Dev Mode Config
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshDevModeConfigDevModeRefreshPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.refreshDevModeConfigDevModeRefreshPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Enable/disable Developer Mode.  - true from false:     * backup existing DEV_MODE_DIR if it exists     * refresh DEV_MODE_DIR from OEM_CORE_DIR     * set cm4 flag     * set CORE_CFG to DEV_MODE_CORE_CFG     * restart klipper - false from true:     * set CORE_CFG to OEM_CORE_CFG     * restart klipper - no state change: no-op
         * @summary Set Dev Mode
         * @param {DevModeToggle} devModeToggle 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setDevModeDevModePost(devModeToggle: DevModeToggle, options?: RawAxiosRequestConfig): AxiosPromise<DevModeStatus> {
            return localVarFp.setDevModeDevModePost(devModeToggle, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DevModeApi - object-oriented interface
 * @export
 * @class DevModeApi
 * @extends {BaseAPI}
 */
export class DevModeApi extends BaseAPI {
    /**
     * Dev mode is TRUE if CORE_CFG == DEV_MODE_CORE_CFG, FALSE if CORE_CFG == OEM_CORE_CFG, ERROR otherwise.
     * @summary Get Dev Mode Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevModeApi
     */
    public getDevModeStatusDevModeGet(options?: RawAxiosRequestConfig) {
        return DevModeApiFp(this.configuration).getDevModeStatusDevModeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a timestamped backup of the current dev-mode working directory. Only valid while dev mode is enabled.
     * @summary Manual Backup
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevModeApi
     */
    public manualBackupDevModeBackupPost(options?: RawAxiosRequestConfig) {
        return DevModeApiFp(this.configuration).manualBackupDevModeBackupPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Refresh the developer-mode working copy from OEM core. Only valid while dev mode is enabled.  Steps:   * backup DEV_MODE_DIR to backups/<timestamp> (excluding backups)   * clear DEV_MODE_DIR except \'backups\'   * copy OEM_CORE_DIR into DEV_MODE_DIR
     * @summary Refresh Dev Mode Config
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevModeApi
     */
    public refreshDevModeConfigDevModeRefreshPost(options?: RawAxiosRequestConfig) {
        return DevModeApiFp(this.configuration).refreshDevModeConfigDevModeRefreshPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enable/disable Developer Mode.  - true from false:     * backup existing DEV_MODE_DIR if it exists     * refresh DEV_MODE_DIR from OEM_CORE_DIR     * set cm4 flag     * set CORE_CFG to DEV_MODE_CORE_CFG     * restart klipper - false from true:     * set CORE_CFG to OEM_CORE_CFG     * restart klipper - no state change: no-op
     * @summary Set Dev Mode
     * @param {DevModeToggle} devModeToggle 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevModeApi
     */
    public setDevModeDevModePost(devModeToggle: DevModeToggle, options?: RawAxiosRequestConfig) {
        return DevModeApiFp(this.configuration).setDevModeDevModePost(devModeToggle, options).then((request) => request(this.axios, this.basePath));
    }
}

