/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { OTASetProgressRequest } from '../models';
// @ts-ignore
import type { OTAStartRequest } from '../models';
// @ts-ignore
import type { OTAStatus } from '../models';
// @ts-ignore
import type { VerifyRequest } from '../models';
/**
 * UpdateApi - axios parameter creator
 * @export
 */
export const UpdateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Trigger a check for updates from server.
         * @summary Ota Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaCheckUpdateCheckServerPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/check_server`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Commit to the installed update.
         * @summary Ota Commit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaCommitUpdateCommitPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/commit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Set Progress
         * @param {OTASetProgressRequest} oTASetProgressRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaSetProgressUpdateSetProgressPost: async (oTASetProgressRequest: OTASetProgressRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'oTASetProgressRequest' is not null or undefined
            assertParamExists('otaSetProgressUpdateSetProgressPost', 'oTASetProgressRequest', oTASetProgressRequest)
            const localVarPath = `/update/set-progress`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(oTASetProgressRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Start
         * @param {OTAStartRequest} oTAStartRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaStartUpdateStartPost: async (oTAStartRequest: OTAStartRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'oTAStartRequest' is not null or undefined
            assertParamExists('otaStartUpdateStartPost', 'oTAStartRequest', oTAStartRequest)
            const localVarPath = `/update/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(oTAStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current status of the OTA update service.
         * @summary Ota Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaStatusUpdateStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyAndCommitUpdateVerifyAndCommitPost: async (verifyRequest?: VerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/verify-and-commit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyAndCommitUpdateVerifyAndCommitPost_1: async (verifyRequest?: VerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/verify-and-commit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyUpdateVerifyPost: async (verifyRequest?: VerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyUpdateVerifyPost_2: async (verifyRequest?: VerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UpdateApi - functional programming interface
 * @export
 */
export const UpdateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UpdateApiAxiosParamCreator(configuration)
    return {
        /**
         * Trigger a check for updates from server.
         * @summary Ota Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaCheckUpdateCheckServerPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaCheckUpdateCheckServerPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaCheckUpdateCheckServerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Commit to the installed update.
         * @summary Ota Commit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaCommitUpdateCommitPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaCommitUpdateCommitPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaCommitUpdateCommitPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Set Progress
         * @param {OTASetProgressRequest} oTASetProgressRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaSetProgressUpdateSetProgressPost(oTASetProgressRequest: OTASetProgressRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaSetProgressUpdateSetProgressPost(oTASetProgressRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaSetProgressUpdateSetProgressPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Start
         * @param {OTAStartRequest} oTAStartRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaStartUpdateStartPost(oTAStartRequest: OTAStartRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaStartUpdateStartPost(oTAStartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaStartUpdateStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current status of the OTA update service.
         * @summary Ota Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaStatusUpdateStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OTAStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaStatusUpdateStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaStatusUpdateStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaVerifyAndCommitUpdateVerifyAndCommitPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaVerifyAndCommitUpdateVerifyAndCommitPost_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaVerifyUpdateVerifyPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaVerifyUpdateVerifyPost(verifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaVerifyUpdateVerifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otaVerifyUpdateVerifyPost_2(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otaVerifyUpdateVerifyPost_2(verifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UpdateApi.otaVerifyUpdateVerifyPost_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UpdateApi - factory interface
 * @export
 */
export const UpdateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UpdateApiFp(configuration)
    return {
        /**
         * Trigger a check for updates from server.
         * @summary Ota Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaCheckUpdateCheckServerPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaCheckUpdateCheckServerPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Commit to the installed update.
         * @summary Ota Commit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaCommitUpdateCommitPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaCommitUpdateCommitPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Set Progress
         * @param {OTASetProgressRequest} oTASetProgressRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaSetProgressUpdateSetProgressPost(oTASetProgressRequest: OTASetProgressRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaSetProgressUpdateSetProgressPost(oTASetProgressRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Start
         * @param {OTAStartRequest} oTAStartRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaStartUpdateStartPost(oTAStartRequest: OTAStartRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaStartUpdateStartPost(oTAStartRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current status of the OTA update service.
         * @summary Ota Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaStatusUpdateStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<OTAStatus> {
            return localVarFp.otaStatusUpdateStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Verify And Commit
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyUpdateVerifyPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaVerifyUpdateVerifyPost(verifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ota Verify
         * @param {VerifyRequest} [verifyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otaVerifyUpdateVerifyPost_2(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.otaVerifyUpdateVerifyPost_2(verifyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UpdateApi - object-oriented interface
 * @export
 * @class UpdateApi
 * @extends {BaseAPI}
 */
export class UpdateApi extends BaseAPI {
    /**
     * Trigger a check for updates from server.
     * @summary Ota Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaCheckUpdateCheckServerPost(options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaCheckUpdateCheckServerPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Commit to the installed update.
     * @summary Ota Commit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaCommitUpdateCommitPost(options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaCommitUpdateCommitPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Set Progress
     * @param {OTASetProgressRequest} oTASetProgressRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaSetProgressUpdateSetProgressPost(oTASetProgressRequest: OTASetProgressRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaSetProgressUpdateSetProgressPost(oTASetProgressRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Start
     * @param {OTAStartRequest} oTAStartRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaStartUpdateStartPost(oTAStartRequest: OTAStartRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaStartUpdateStartPost(oTAStartRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current status of the OTA update service.
     * @summary Ota Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaStatusUpdateStatusGet(options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaStatusUpdateStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Verify And Commit
     * @param {VerifyRequest} [verifyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaVerifyAndCommitUpdateVerifyAndCommitPost(verifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Verify And Commit
     * @param {VerifyRequest} [verifyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaVerifyAndCommitUpdateVerifyAndCommitPost_1(verifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Verify
     * @param {VerifyRequest} [verifyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaVerifyUpdateVerifyPost(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaVerifyUpdateVerifyPost(verifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Ota Verify
     * @param {VerifyRequest} [verifyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UpdateApi
     */
    public otaVerifyUpdateVerifyPost_2(verifyRequest?: VerifyRequest, options?: RawAxiosRequestConfig) {
        return UpdateApiFp(this.configuration).otaVerifyUpdateVerifyPost_2(verifyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

