/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Credentials } from '../models';
// @ts-ignore
import type { Device } from '../models';
// @ts-ignore
import type { DeviceWifi } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ResponseGetDetailsWifiShowGetValue } from '../models';
/**
 * WifiApi - axios parameter creator
 * @export
 */
export const WifiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Bring the wifi device down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apDownWifiDeviceDownPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/device/down`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bring the  wifi device up.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apUpWifiDeviceUpPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/device/up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Show all connection profiles
         * @summary Get Details
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailsWifiShowGet: async (ssid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ssid' is not null or undefined
            assertParamExists('getDetailsWifiShowGet', 'ssid', ssid)
            const localVarPath = `/wifi/show`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ssid !== undefined) {
                localVarQueryParameter['ssid'] = ssid;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Connect to an SSID (with optional password).
         * @summary Wifi Connect
         * @param {Credentials} credentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiConnectWifiConnectPost: async (credentials: Credentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentials' is not null or undefined
            assertParamExists('wifiConnectWifiConnectPost', 'credentials', credentials)
            const localVarPath = `/wifi/connect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(credentials, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return the currently active Wi-Fi connection, or null if none.
         * @summary Wifi Current
         * @param {boolean} [update] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiCurrentWifiCurrentGet: async (update?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (update !== undefined) {
                localVarQueryParameter['update'] = update;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disconnect from the current Wi-Fi network.
         * @summary Wifi Disconnect
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiDisconnectWifiDisconnectPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/disconnect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permanently delete the current Wi-Fi connection profile.
         * @summary Wifi Forget
         * @param {string} [ssid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiForgetWifiForgetDelete: async (ssid?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/forget`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ssid !== undefined) {
                localVarQueryParameter['ssid'] = ssid;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Scan for available Wi-Fi networks. Only performs a fresh scan if `rescan` is True and it hasn\'t rescanned in the last SCAN_TTL seconds.
         * @summary Wifi Scan
         * @param {boolean} [rescan] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiScanWifiScanGet: async (rescan?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/scan`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (rescan !== undefined) {
                localVarQueryParameter['rescan'] = rescan;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiStatusWifiDeviceStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/wifi/device/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start or switch to a known connection by its SSID.
         * @summary Wifi Switch
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiSwitchWifiUpPost: async (ssid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ssid' is not null or undefined
            assertParamExists('wifiSwitchWifiUpPost', 'ssid', ssid)
            const localVarPath = `/wifi/up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ssid !== undefined) {
                localVarQueryParameter['ssid'] = ssid;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WifiApi - functional programming interface
 * @export
 */
export const WifiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WifiApiAxiosParamCreator(configuration)
    return {
        /**
         * Bring the wifi device down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apDownWifiDeviceDownPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apDownWifiDeviceDownPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.apDownWifiDeviceDownPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bring the  wifi device up.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apUpWifiDeviceUpPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apUpWifiDeviceUpPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.apUpWifiDeviceUpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Show all connection profiles
         * @summary Get Details
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetailsWifiShowGet(ssid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: ResponseGetDetailsWifiShowGetValue; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDetailsWifiShowGet(ssid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.getDetailsWifiShowGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Connect to an SSID (with optional password).
         * @summary Wifi Connect
         * @param {Credentials} credentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiConnectWifiConnectPost(credentials: Credentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiConnectWifiConnectPost(credentials, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiConnectWifiConnectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return the currently active Wi-Fi connection, or null if none.
         * @summary Wifi Current
         * @param {boolean} [update] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiCurrentWifiCurrentGet(update?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceWifi>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiCurrentWifiCurrentGet(update, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiCurrentWifiCurrentGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disconnect from the current Wi-Fi network.
         * @summary Wifi Disconnect
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiDisconnectWifiDisconnectPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiDisconnectWifiDisconnectPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiDisconnectWifiDisconnectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permanently delete the current Wi-Fi connection profile.
         * @summary Wifi Forget
         * @param {string} [ssid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiForgetWifiForgetDelete(ssid?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiForgetWifiForgetDelete(ssid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiForgetWifiForgetDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Scan for available Wi-Fi networks. Only performs a fresh scan if `rescan` is True and it hasn\'t rescanned in the last SCAN_TTL seconds.
         * @summary Wifi Scan
         * @param {boolean} [rescan] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiScanWifiScanGet(rescan?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DeviceWifi>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiScanWifiScanGet(rescan, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiScanWifiScanGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiStatusWifiDeviceStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiStatusWifiDeviceStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiStatusWifiDeviceStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Start or switch to a known connection by its SSID.
         * @summary Wifi Switch
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wifiSwitchWifiUpPost(ssid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wifiSwitchWifiUpPost(ssid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WifiApi.wifiSwitchWifiUpPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WifiApi - factory interface
 * @export
 */
export const WifiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WifiApiFp(configuration)
    return {
        /**
         * Bring the wifi device down.
         * @summary Ap Down
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apDownWifiDeviceDownPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apDownWifiDeviceDownPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Bring the  wifi device up.
         * @summary Ap Up
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apUpWifiDeviceUpPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apUpWifiDeviceUpPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Show all connection profiles
         * @summary Get Details
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetailsWifiShowGet(ssid: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: ResponseGetDetailsWifiShowGetValue; }> {
            return localVarFp.getDetailsWifiShowGet(ssid, options).then((request) => request(axios, basePath));
        },
        /**
         * Connect to an SSID (with optional password).
         * @summary Wifi Connect
         * @param {Credentials} credentials 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiConnectWifiConnectPost(credentials: Credentials, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.wifiConnectWifiConnectPost(credentials, options).then((request) => request(axios, basePath));
        },
        /**
         * Return the currently active Wi-Fi connection, or null if none.
         * @summary Wifi Current
         * @param {boolean} [update] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiCurrentWifiCurrentGet(update?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<DeviceWifi> {
            return localVarFp.wifiCurrentWifiCurrentGet(update, options).then((request) => request(axios, basePath));
        },
        /**
         * Disconnect from the current Wi-Fi network.
         * @summary Wifi Disconnect
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiDisconnectWifiDisconnectPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.wifiDisconnectWifiDisconnectPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Permanently delete the current Wi-Fi connection profile.
         * @summary Wifi Forget
         * @param {string} [ssid] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiForgetWifiForgetDelete(ssid?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.wifiForgetWifiForgetDelete(ssid, options).then((request) => request(axios, basePath));
        },
        /**
         * Scan for available Wi-Fi networks. Only performs a fresh scan if `rescan` is True and it hasn\'t rescanned in the last SCAN_TTL seconds.
         * @summary Wifi Scan
         * @param {boolean} [rescan] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiScanWifiScanGet(rescan?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<DeviceWifi>> {
            return localVarFp.wifiScanWifiScanGet(rescan, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Wifi Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiStatusWifiDeviceStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<Device> {
            return localVarFp.wifiStatusWifiDeviceStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Start or switch to a known connection by its SSID.
         * @summary Wifi Switch
         * @param {string} ssid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wifiSwitchWifiUpPost(ssid: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.wifiSwitchWifiUpPost(ssid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WifiApi - object-oriented interface
 * @export
 * @class WifiApi
 * @extends {BaseAPI}
 */
export class WifiApi extends BaseAPI {
    /**
     * Bring the wifi device down.
     * @summary Ap Down
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public apDownWifiDeviceDownPost(options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).apDownWifiDeviceDownPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Bring the  wifi device up.
     * @summary Ap Up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public apUpWifiDeviceUpPost(options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).apUpWifiDeviceUpPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Show all connection profiles
     * @summary Get Details
     * @param {string} ssid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public getDetailsWifiShowGet(ssid: string, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).getDetailsWifiShowGet(ssid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Connect to an SSID (with optional password).
     * @summary Wifi Connect
     * @param {Credentials} credentials 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiConnectWifiConnectPost(credentials: Credentials, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiConnectWifiConnectPost(credentials, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return the currently active Wi-Fi connection, or null if none.
     * @summary Wifi Current
     * @param {boolean} [update] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiCurrentWifiCurrentGet(update?: boolean, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiCurrentWifiCurrentGet(update, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Disconnect from the current Wi-Fi network.
     * @summary Wifi Disconnect
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiDisconnectWifiDisconnectPost(options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiDisconnectWifiDisconnectPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permanently delete the current Wi-Fi connection profile.
     * @summary Wifi Forget
     * @param {string} [ssid] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiForgetWifiForgetDelete(ssid?: string, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiForgetWifiForgetDelete(ssid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Scan for available Wi-Fi networks. Only performs a fresh scan if `rescan` is True and it hasn\'t rescanned in the last SCAN_TTL seconds.
     * @summary Wifi Scan
     * @param {boolean} [rescan] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiScanWifiScanGet(rescan?: boolean, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiScanWifiScanGet(rescan, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Wifi Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiStatusWifiDeviceStatusGet(options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiStatusWifiDeviceStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start or switch to a known connection by its SSID.
     * @summary Wifi Switch
     * @param {string} ssid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WifiApi
     */
    public wifiSwitchWifiUpPost(ssid: string, options?: RawAxiosRequestConfig) {
        return WifiApiFp(this.configuration).wifiSwitchWifiUpPost(ssid, options).then((request) => request(this.axios, this.basePath));
    }
}

