/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APCredentials
 */
export interface APCredentials {
    /**
     * 
     * @type {string}
     * @memberof APCredentials
     */
    'ssid': string;
    /**
     * 
     * @type {string}
     * @memberof APCredentials
     */
    'password'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof APCredentials
     */
    'autoconnect'?: boolean | null;
}

