/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DevModeConsentChallenge
 */
export interface DevModeConsentChallenge {
    /**
     * 
     * @type {string}
     * @memberof DevModeConsentChallenge
     */
    'challenge_id': string;
    /**
     * 
     * @type {number}
     * @memberof DevModeConsentChallenge
     */
    'expires_at': number;
    /**
     * 
     * @type {number}
     * @memberof DevModeConsentChallenge
     */
    'expires_in_seconds': number;
    /**
     * 
     * @type {string}
     * @memberof DevModeConsentChallenge
     */
    'instruction': string;
}

