/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DevModeStatus
 */
export interface DevModeStatus {
    /**
     * 
     * @type {boolean}
     * @memberof DevModeStatus
     */
    'enabled': boolean;
    /**
     * 
     * @type {string}
     * @memberof DevModeStatus
     */
    'core_cfg': string;
}

