/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceWifi
 */
export interface DeviceWifi {
    /**
     * 
     * @type {boolean}
     * @memberof DeviceWifi
     */
    'in_use': boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceWifi
     */
    'ssid': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceWifi
     */
    'bssid': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceWifi
     */
    'mode': string;
    /**
     * 
     * @type {number}
     * @memberof DeviceWifi
     */
    'chan': number;
    /**
     * 
     * @type {number}
     * @memberof DeviceWifi
     */
    'freq': number;
    /**
     * 
     * @type {number}
     * @memberof DeviceWifi
     */
    'rate': number;
    /**
     * 
     * @type {number}
     * @memberof DeviceWifi
     */
    'signal': number;
    /**
     * 
     * @type {string}
     * @memberof DeviceWifi
     */
    'security': string;
}

