/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'device': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'device_type': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'connection': string | null;
}

