/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceStatus
 */
export interface DeviceStatus {
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    'device': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    'device_type': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    'connection': string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceStatus
     */
    'state_reason'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceStatus
     */
    'user_disconnected'?: boolean;
}

