/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * State of the OTA update service.
 * @export
 * @enum {string}
 */

export const OTAState = {
    Idle: 'idle',
    Installing: 'installing',
    Committing: 'committing',
    Failed: 'failed'
} as const;

export type OTAState = typeof OTAState[keyof typeof OTAState];



