/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OTAConfiguration } from './otaconfiguration';
// May contain unused imports in some cases
// @ts-ignore
import type { OTAState } from './otastate';
// May contain unused imports in some cases
// @ts-ignore
import type { RugixBuildInfo } from './rugix-build-info';
// May contain unused imports in some cases
// @ts-ignore
import type { RugixSystemInfo } from './rugix-system-info';

/**
 * Status of the OTA update service.
 * @export
 * @interface OTAStatus
 */
export interface OTAStatus {
    /**
     * 
     * @type {OTAState}
     * @memberof OTAStatus
     */
    'state': OTAState;
    /**
     * 
     * @type {string}
     * @memberof OTAStatus
     */
    'error'?: string | null;
    /**
     * 
     * @type {OTAConfiguration}
     * @memberof OTAStatus
     */
    'configuration'?: OTAConfiguration | null;
    /**
     * 
     * @type {RugixBuildInfo}
     * @memberof OTAStatus
     */
    'build_info'?: RugixBuildInfo | null;
    /**
     * 
     * @type {RugixSystemInfo}
     * @memberof OTAStatus
     */
    'system_info'?: RugixSystemInfo | null;
    /**
     * 
     * @type {string}
     * @memberof OTAStatus
     */
    'target_version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OTAStatus
     */
    'current_version'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OTAStatus
     */
    'update_available'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OTAStatus
     */
    'requires_commit'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OTAStatus
     */
    'progress'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OTAStatus
     */
    'last_checked'?: string | null;
}



