/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to start an OTA update.
 * @export
 * @interface OTAStartRequest
 */
export interface OTAStartRequest {
    /**
     * 
     * @type {string}
     * @memberof OTAStartRequest
     */
    'url'?: string | null;
}

