/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RugixReleaseInfo } from './rugix-release-info';

/**
 * Rugix Bakery build information.
 * @export
 * @interface RugixBuildInfo
 */
export interface RugixBuildInfo {
    /**
     * 
     * @type {string}
     * @memberof RugixBuildInfo
     */
    'name': string;
    /**
     * 
     * @type {RugixReleaseInfo}
     * @memberof RugixBuildInfo
     */
    'release': RugixReleaseInfo;
}

