/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Rugix Bakery release information.
 * @export
 * @interface RugixReleaseInfo
 */
export interface RugixReleaseInfo {
    /**
     * 
     * @type {string}
     * @memberof RugixReleaseInfo
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RugixReleaseInfo
     */
    'version': string;
}

