/* tslint:disable */
/* eslint-disable */
/**
 * SmartKnob AUX HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Boot information of the system.
 * @export
 * @interface RugixSystemBootInfo
 */
export interface RugixSystemBootInfo {
    /**
     * 
     * @type {string}
     * @memberof RugixSystemBootInfo
     */
    'defaultGroup'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RugixSystemBootInfo
     */
    'activeGroup'?: string | null;
}

